FROM 8.3-rc-alpine3.19
RUN apt-get install -y php

ENV COMPOSER_ALLOW_SUPERUSER=1

EXPOSE 80
WORKDIR /app
COPY I dest

# PHP Extensions
RUN docker-php-ext-install -j$(nproc) opcache pdo_mysql
COPY conf/php.ini /usr/local/etc/php/conf.d/app.ini

# Apache
COPY errors /errors
COPY conf/vhost.conf /etc/apache2/sites-available/000-default.conf
COPY conf/apache.conf /etc/apache2/conf-available/z-app.conf
COPY index.php /app/index.php

RUN a2enmod rewrite remoteip && \
    a2enconf z-app



